LIBNAME NH 'C:\輔仁大學臨時工\中醫附醫';RUN;
LIBNAME TEMP 'C:\輔仁大學臨時工\中醫附醫\TEMP';RUN;
LIBNAME NHIRD 'D:\NHIRD'; RUN;


PROC IMPORT OUT = CODE_ICD  /*從EXCEL檔建立TABLE*/ 
	DATAFILE = "C:\輔仁大學臨時工\中醫附醫\診斷碼整理to宇文.xlsx"
	DBMS = EXCEL REPLACE;
	SHEET = icd_use;
;
QUIT;
PROC IMPORT OUT = CODE_MEDICINE  /*從EXCEL檔建立TABLE*/ 
	DATAFILE = "C:\輔仁大學臨時工\中醫附醫\中藥記錄.xlsx"
	DBMS = EXCEL REPLACE;
	SHEET = 單方;
;
QUIT;
PROC IMPORT OUT = CODE_MEDICINE_2  /*從EXCEL檔建立TABLE*/ 
	DATAFILE = "C:\輔仁大學臨時工\中醫附醫\中藥記錄.xlsx"
	DBMS = EXCEL REPLACE;
	SHEET = 複方;
;
QUIT;
DATA TEMP.ICD_C01; /*甲狀腺惡性腫瘤*/
	INPUT ICD $;
	CARDS; 
193
; 
RUN;
PROC SQL; /*惡性腫瘤*/ 
CREATE TABLE TEMP.ICD_C02 AS
SELECT DISTINCT
	A.ICD
FROM CODE_ICD AS A
WHERE 
	A.NHI_type LIKE 'ICD9' AND A.content LIKE '甲狀腺癌以外的惡性腫瘤' 
;
QUIT;
PROC SQL; /*中藥*/ 
CREATE TABLE TEMP.ICD_C03 AS
SELECT DISTINCT
	A.V01 AS ORDER_CODE
FROM CODE_MEDICINE AS A
UNION
SELECT DISTINCT
	B.V01 AS ORDER_CODE
FROM CODE_MEDICINE_2  AS B
;
QUIT;
%LET SSS = 1997;
%LET SS = 2000; 
%LET EE = 2013;  

DATA _NULL_; /*取出C01~C02  CD DD DATA*/
    DO ICD="C01","C02";
    CALL EXECUTE("PROC SQL;");
    DO YEAR=&SS TO &EE;
        CALL EXECUTE("CREATE TABLE CD_"||ICD||STRIP(YEAR)||" AS
            SELECT DISTINCT 
			A.ID,
			A.ID_BIRTHDAY,
			'CD' AS TYPE,  
			A.CASE_TYPE,
			A.FUNC_DATE,
			ACODE_ICD9_1 AS ICD9_1,
			ACODE_ICD9_2 AS ICD9_2,
			ACODE_ICD9_3 AS ICD9_3
            FROM NHIRD.CD"||STRIP(YEAR)||" AS A
            WHERE
                SUBSTR(ACODE_ICD9_1,1,3) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ACODE_ICD9_2,1,3) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ACODE_ICD9_3,1,3) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ACODE_ICD9_1,1,4) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ACODE_ICD9_2,1,4) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ACODE_ICD9_3,1,4) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ACODE_ICD9_1,1,5) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ACODE_ICD9_2,1,5) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ACODE_ICD9_3,1,5) IN (SELECT ICD FROM TEMP.ICD_"||ICD||")
                ;");
        CALL EXECUTE("CREATE TABLE DD_"||ICD||STRIP(YEAR)||" AS
            SELECT 
			A.ID,
			A.ID_BIRTHDAY,
			'DD' AS TYPE,
			A.CASE_TYPE,
			A.IN_DATE AS FUNC_DATE,
			ICD9CM_CODE AS ICD9_1,
			ICD9CM_CODE_1 AS ICD9_2,
			ICD9CM_CODE_2 AS ICD9_3,
			ICD9CM_CODE_3 AS ICD9_4,
			ICD9CM_CODE_4 AS ICD9_5
            FROM NHIRD.DD"||STRIP(YEAR)||" AS A
            WHERE
                SUBSTR(ICD9CM_CODE,1,3) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9CM_CODE_1,1,3) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9CM_CODE_2,1,3) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9CM_CODE_3,1,3) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9CM_CODE_4,1,3) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9CM_CODE,1,4) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9CM_CODE_1,1,4) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9CM_CODE_2,1,4) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9CM_CODE_3,1,4) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9CM_CODE_4,1,4) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9CM_CODE,1,5) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9CM_CODE_1,1,5) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9CM_CODE_2,1,5) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9CM_CODE_3,1,5) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9CM_CODE_4,1,5) IN (SELECT ICD FROM TEMP.ICD_"||ICD||")
                ;");
    END;
    CALL EXECUTE("QUIT;");
    END;
RUN;

DATA _NULL_; /*合併檔案*/
    DO ICD="C01","C02";
    CALL EXECUTE("DATA NH."||ICD||";");
    CALL EXECUTE("SET CD_"||ICD||"2000-CD_"||ICD||"2013 DD_"||ICD||"2000-DD_"||ICD||"2013;");
    CALL EXECUTE("RUN;");
    END;
RUN;
DATA _NULL_; /*取出C01  HV DATA*/
    DO ICD="C01";
    CALL EXECUTE("PROC SQL;");
    DO YEAR=&SSS TO 2009;
        CALL EXECUTE("CREATE TABLE HV_"||ICD||STRIP(YEAR)||" AS
            SELECT DISTINCT 
			A.ID,
			A.APPL_DATE,
			DISE_CODE AS ICD9
            FROM NHIRD.HV"||STRIP(YEAR)||" AS A
            WHERE
                SUBSTR(ICD9,1,3) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9,1,4) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9,1,5) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") 
                ;");
    END;
    CALL EXECUTE("QUIT;");
    END;
RUN;
DATA _NULL_; /*取出C01  HV DATA*/
    DO ICD="C01";
    CALL EXECUTE("PROC SQL;");
    DO YEAR=2010 TO 2013;
        CALL EXECUTE("CREATE TABLE HV_"||ICD||STRIP(YEAR)||" AS
            SELECT DISTINCT 
			A.ID,
			A.APPL_DATE,
			ICD9CM_CODE AS ICD9
            FROM NHIRD.HV"||STRIP(YEAR)||" AS A
            WHERE
                SUBSTR(ICD9,1,3) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9,1,4) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") OR
                SUBSTR(ICD9,1,5) IN (SELECT ICD FROM TEMP.ICD_"||ICD||") 
                ;");
    END;
    CALL EXECUTE("QUIT;");
    END;
RUN;
DATA _NULL_; /*合併檔案*/
    DO ICD="C01";
    CALL EXECUTE("DATA NH.HV"||ICD||";");
    CALL EXECUTE("SET HV_"||ICD||"1997-HV_"||ICD||"2013;");
    CALL EXECUTE("RUN;");
    END;
RUN;

DATA _NULL_; /*取出曾經紀錄死亡的人的DATA*/
    DO ICD="DEA";
    CALL EXECUTE("PROC SQL;");
    DO YEAR=&SS TO &EE;
        CALL EXECUTE("CREATE TABLE DD_"||ICD||STRIP(YEAR)||" AS
            SELECT 
			A.ID,
			A.ID_BIRTHDAY,
			'DD' AS TYPE, 
			A.CASE_TYPE,
			A.IN_DATE AS FUNC_DATE,
			TRAN_CODE,
			ICD9CM_CODE AS ICD9_1,
			ICD9CM_CODE_1 AS ICD9_2,
			ICD9CM_CODE_2 AS ICD9_3,
			ICD9CM_CODE_3 AS ICD9_4,
			ICD9CM_CODE_4 AS ICD9_5,
			ICD_OP_CODE,
			ICD_OP_CODE_1,
			ICD_OP_CODE_2,
			ICD_OP_CODE_3,
			ICD_OP_CODE_4
            FROM NHIRD.DD"||STRIP(YEAR)||" AS A
            WHERE TRAN_CODE IN ('4','A')
                ;");
    END;
    CALL EXECUTE("QUIT;");
    END;
RUN;

DATA _NULL_; /*合併檔案*/
    DO ICD="DEA";
    CALL EXECUTE("DATA NH."||ICD||";");
    CALL EXECUTE("SET DD_"||ICD||"2000-DD_"||ICD||"2013;");
    CALL EXECUTE("RUN;");
    END;
RUN;

DATA _NULL_; /*取出藥物檔do*/
    DO ICD="C03";
    CALL EXECUTE("PROC SQL;");
    DO YEAR=&SS TO &EE;
        CALL EXECUTE("CREATE TABLE DO_"||ICD||STRIP(YEAR)||" AS
            SELECT DISTINCT
			A.FEE_YM,
			A.APPL_TYPE,  
			A.HOSP_ID,
			A.APPL_DATE,
			A.CASE_TYPE,
			A.SEQ_NO,
			A.ORDER_CODE,
			'DO' AS TYPE
            FROM NHIRD.DO"||STRIP(YEAR)||" AS A
            WHERE
                ORDER_CODE IN (SELECT ORDER_CODE FROM ICD_"||ICD||")
                ;");
    END;
    CALL EXECUTE("QUIT;");
    END;
RUN;
DATA _NULL_; /*合併檔案*/
    DO ICD="C03";
    CALL EXECUTE("DATA DO"||ICD||";");
    CALL EXECUTE("SET DO_"||ICD||"2000-DO_"||ICD||"2013;");
    CALL EXECUTE("RUN;");
    END;
RUN;
DATA _NULL_; /*取出藥物檔oo*/
    DO ICD="C03";
    CALL EXECUTE("PROC SQL;");
    DO YEAR=&SS TO &EE;
        CALL EXECUTE("CREATE TABLE OO_"||ICD||STRIP(YEAR)||" AS
            SELECT DISTINCT
			A.FEE_YM,
			A.APPL_TYPE,  
			A.HOSP_ID,
			A.APPL_DATE,
			A.CASE_TYPE,
			A.SEQ_NO,
			A.DRUG_NO AS ORDER_CODE,
			'OO' AS TYPE
            FROM NHIRD.OO"||STRIP(YEAR)||" AS A
            WHERE
                DRUG_NO IN (SELECT ORDER_CODE FROM ICD_"||ICD||")
                ;");
    END;
    CALL EXECUTE("QUIT;");
    END;
RUN;
DATA _NULL_; /*合併檔案*/
    DO ICD="C03";
    CALL EXECUTE("DATA OO"||ICD||";");
    CALL EXECUTE("SET  OO_"||ICD||"2000-OO_"||ICD||"2013;");
    CALL EXECUTE("RUN;");
    END;
RUN;
DATA _NULL_; /*串檔*/
    DO ICD="C03";
    CALL EXECUTE("PROC SQL;");
    DO YEAR=&SS TO &EE;
        CALL EXECUTE("CREATE TABLE DD_"||ICD||STRIP(YEAR)||" AS
            SELECT DISTINCT
			A.ID,
			A.ID_BIRTHDAY,
			'DD' AS TYPE,
			A.IN_DATE AS FUNC_DATE,
			B.ORDER_CODE
            FROM NHIRD.DD"||STRIP(YEAR)||" AS A
			INNER JOIN DO"||ICD||" AS B ON (A.FEE_YM = B.FEE_YM AND A.APPL_TYPE = B.APPL_TYPE AND A.HOSP_ID = B.HOSP_ID AND A.APPL_DATE = B.APPL_DATE AND A.CASE_TYPE = B.CASE_TYPE AND A.SEQ_NO = B.SEQ_NO)
			;");
        CALL EXECUTE("CREATE TABLE CD_"||ICD||STRIP(YEAR)||" AS
            SELECT DISTINCT
			A.ID,
			A.ID_BIRTHDAY,
			'CD' AS TYPE,
			A.FUNC_DATE,
			B.ORDER_CODE
            FROM NHIRD.CD"||STRIP(YEAR)||" AS A
			INNER JOIN OO"||ICD||" AS B ON (A.FEE_YM = B.FEE_YM AND A.APPL_TYPE = B.APPL_TYPE AND A.HOSP_ID = B.HOSP_ID AND A.APPL_DATE = B.APPL_DATE AND A.CASE_TYPE = B.CASE_TYPE AND A.SEQ_NO = B.SEQ_NO)
			;");
    END;
    CALL EXECUTE("QUIT;");
    END;
RUN;
DATA _NULL_; /*合併檔案*/
    DO ICD="C03";
    CALL EXECUTE("DATA NH."||ICD||";");
    CALL EXECUTE("SET DD_"||ICD||"2000-DD_"||ICD||"2013 CD_"||ICD||"2000-CD_"||ICD||"2013;");
    CALL EXECUTE("RUN;");
    END;
RUN;

PROC SQL; /*ID進行串檔*/
CREATE TABLE NH.CASE_00 AS 
SELECT DISTINCT 
	A.ID,
	MIN(FUNC_DATE) AS FIRST_DATE,
	B.ID_SEX,
	CATS(B.ID_BIRTHDAY,'15') AS ID_BIRTHDAY,
	FLOOR(YRDIF(INPUT(CATS(SUBSTR(B.ID_BIRTHDAY,1,4),'0101'),YYMMDD8.),INPUT(MIN(FUNC_DATE),YYMMDD8.),'ACT/ACT')) AS AGE
FROM NH.C01 AS A
LEFT JOIN NHIRD.ID2005 AS B ON A.ID = B.ID
GROUP BY A.ID
;
QUIT;

PROC SQL; /*排除條件*/  
CREATE TABLE TEMP.EXL02 AS 
SELECT DISTINCT A.ID
FROM NH.CASE_00 AS A
INNER JOIN NH.C02 AS B ON A.ID = B.ID 
WHERE SUBSTR(FIRST_DATE,1,4) IN ("2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013",)
;
QUIT;

PROC SQL; /*額外加入表格並以0和1標籤方便計算人數*/
CREATE TABLE NH.CASE_01 AS 
SELECT DISTINCT A.*,
    CASE WHEN A.AGE > 18 THEN 1 ELSE 0 END AS EXL_01,
    CASE WHEN B1.ID IS  NULL THEN 1 ELSE 0 END AS EXL_02,
    CASE WHEN B2.ID IS  NULL THEN 1 ELSE 0 END AS EXL_03,
    CASE WHEN B3.ID IS  NULL THEN 1 ELSE 0 END AS EXL_04,
	CASE WHEN B4.ID IS  NULL THEN 1 ELSE 0 END AS EXL_05,
	CASE WHEN B5.ID IS  NULL THEN 1 ELSE 0 END AS EXL_06,
	CASE WHEN B6.ID IS  NULL THEN 1 ELSE 0 END AS EXL_07,
	CASE WHEN B7.ID IS  NULL THEN 1 ELSE 0 END AS EXL_08,
	CASE WHEN B8.ID IS  NULL THEN 1 ELSE 0 END AS EXL_09
FROM NH.CASE_00 AS A
LEFT JOIN TEMP.EXL02 AS B1 ON A.ID = B1.ID
LEFT JOIN TEMP.EXL03 AS B2 ON A.ID = B2.ID
LEFT JOIN TEMP.EXL04 AS B3 ON A.ID = B3.ID
LEFT JOIN TEMP.EXL05 AS B4 ON A.ID = B4.ID
LEFT JOIN TEMP.EXL06 AS B5 ON A.ID = B5.ID
LEFT JOIN TEMP.EXL07 AS B6 ON A.ID = B6.ID
LEFT JOIN TEMP.EXL08 AS B7 ON A.ID = B7.ID
LEFT JOIN TEMP.EXL09 AS B8 ON A.ID = B8.ID
WHERE SUBSTR(FIRST_DATE,1,4) IN ("2007","2008","2009","2010","2011","2012")
;
QUIT;